Repository Kas73/SOEN-341-Project, pull requests merged in 2022-02, with the labels that each got.

#31 Added dependencies to package.json and added .gitignore
  .gitignore
  package.json
Labels: Task, back-end

#35 Added Login and AddNewProduct pages #32 #33
  public/index.html
  src/App.css
  src/App.js
  src/components/AddNewProduct.jsx
  src/components/Home.jsx
  src/components/Login.jsx
  src/components/layout/Footer.jsx
  src/components/layout/Navbar.jsx
  src/index.js
Labels: Task, front-end

#39 Adding front-end for sign-up page
  src/App.js
  src/components/SignUp.jsx
Labels: Task, front-end

#48 Fixing Broken Create POST request
  client/src/components/AddNewProduct.jsx
Labels: front-end, back-end

#52 Edited the layout of Create account page.
  client/src/App.css
  client/src/components/SignUp.jsx
Labels: Task, front-end
