Repository Kas73/SOEN-341-Project, pull requests merged in 2022-04, with the labels that each got.

#98 Added payments method object to users database, issue #97
  models/users.model.js
  routes/users.routes.js
Labels: Task, back-end

#99 Search for a product results page #25
  client/src/App.css
  client/src/App.js
  client/src/components/SearchResults.jsx
  client/src/components/layout/Navbar.jsx
  routes/products.routes.js
Labels: feature, front-end, back-end

#104 Browsing by Category and Adding products with Categories
  client/package-lock.json
  client/src/components/AddNewProduct.jsx
  client/src/components/Home.jsx
  client/src/components/ProductList.jsx
  models/categories.model.js
  models/products.model.js
  routes/categories.routes.js
  routes/products.routes.js
  server.js
Labels: front-end, back-end

#110 User can no longer set quantities below 1 on cart page #95
  client/src/components/Cart.jsx
Labels: front-end

#112 CI testing
  .github/workflows/node.js.yml
  karma.conf.js
  package-lock.json
  package.json
  spec/support/jasmine.json
  spec/testSpec.spec.js
Labels: testing

#114 Fix the look of the increment and decrement quantity buttons on the product details page #94
  client/src/components/DetailsPage.jsx
Labels: Task, front-end

#113 Fixed the look of the cart on the checkout page. Display the bill. #66
  client/src/App.css
  client/src/components/Checkout.jsx
  client/src/components/CheckoutListRow.jsx
Labels: Task, front-end

#118 Changed decrement function for quantity so that it cannot go below 0
  client/src/components/DetailsPage.jsx
Labels: front-end

#119 Admin cookie frront-end and back-end
  client/src/components/Login.jsx
  client/src/components/SignUp.jsx
  client/src/components/layout/Navbar.jsx
  models/users.model.js
  routes/users.routes.js
Labels: Task, front-end, back-end

#123 Adding unit tests for the productList component
  client/babel.config.js
  client/jest.config.js
  client/package-lock.json
  client/package.json
  client/src/components/ProductList.jsx
  client/tests/data/dummyCategory.data.json
  client/tests/data/dummyProduct.data.json
  client/tests/productList.test.js
  karma.conf.js
  package.json
  spec/support/jasmine.json
  spec/testSpec.spec.js
Labels: testing

#133 Fix order successful page #132
  client/src/components/OrderSuccessful.jsx
Labels: front-end

#130 Implemented some unit tests for the login page
  client/src/components/Login.jsx
  client/tests/data/dummyUser.data.json
  client/tests/login.test.js
Labels: testing

#134 Added footer #121
  client/src/components/layout/Footer.jsx
Labels: front-end

#135 Removed unnecessary inputs from checkout form #129
  client/src/components/Checkout.jsx
Labels: Task, front-end

#137 Added basic unit tests for OrderList object #136
  client/src/components/OrderList.jsx
  client/src/components/OrderProductList.jsx
  client/tests/data/dummyOrder.data.json
  client/tests/orderList.test.js
Labels: testing

#139 Fix bug where order is not processed when clicking place order
  client/src/components/Checkout.jsx
Labels: front-end
