Repository Kas73/SOEN-341-Project, pull requests merged in 2022-03, with the labels that each got.

#56 Refactor login and signup Front-End Only
  client/src/App.js
  client/src/components/Home.jsx
  client/src/components/Login.jsx
  client/src/components/SignUp.jsx
Labels: front-end

#59 Added Schema, route for Users DB, refactored SignUp and Login page #58
  client/package-lock.json
  client/src/components/Login.jsx
  client/src/components/SignUp.jsx
  models/users.model.js
  package-lock.json
  routes/users.routes.js
  server.js
Labels: Task, front-end, back-end

#53 added add product link for admin users to navbar jsx
  client/src/components/layout/Navbar.jsx
Labels: Task, front-end

#61 Refactored HTML of checkout page so that it is now a React Component
  client/src/App.js
  client/src/components/Checkout.jsx
Labels: front-end

#72 Cookies for user login
  client/package-lock.json
  client/package.json
  client/src/components/Home.jsx
  client/src/components/Login.jsx
  client/src/components/SignUp.jsx
  client/src/components/layout/Navbar.jsx
  client/src/index.js
Labels: front-end

#77 Refactor AddNewProducts and Checkout Page to no longer extend React.Component and fixed login/signup bug
  client/src/components/AddNewProduct.jsx
  client/src/components/Checkout.jsx
  client/src/components/Login.jsx
  client/src/components/SignUp.jsx
Labels: front-end

#78 Add cart frontend and backend #75
  client/package-lock.json
  client/src/App.css
  client/src/App.js
  client/src/components/Cart.jsx
  client/src/components/CartRow.jsx
  client/src/components/layout/Navbar.jsx
  models/carts.model.js
  routes/carts.routes.js
  server.js
Labels: Task, front-end, back-end

#80 added a grid to ProductList with linked names and images
  client/package-lock.json
  client/src/App.css
  client/src/components/ProductList.jsx
  package-lock.json
Labels: Task, front-end

#84 Refactored products model and routes/pages to match the new model.
  client/src/components/AddNewProduct.jsx
  client/src/components/ProductList.jsx
  models/products.model.js
  routes/products.routes.js
  server.js
Labels: Task, front-end, back-end

#87 Logout redirects to Home page
  client/src/components/layout/Navbar.jsx
Labels: Task, front-end

#93 Implementing basic cart page functionalities
  client/src/components/Cart.jsx
  client/src/components/CartRow.jsx
Labels: front-end, back-end
